collision_monitor:
  ros__parameters:
    base_frame_id: base_link
    odom_frame_id: odom
    cmd_vel_in_topic: "cmd_vel_smoothed"   # from nav2_velocity_smoother
    cmd_vel_out_topic: "cmd_vel"           # to your base / controller
    observation_sources: ["scan"]
    scan:
      type: "scan"
      topic: "scan"
      enabled: True
    polygons: ["PolygonStop", "PolygonSlow"]
    PolygonStop:
      type: "polygon"
      points: "[ [0.35, 0.30], [0.35, -0.30], [0.05, -0.30], [0.05, 0.30] ]"
      action_type: "stop"
      enabled: True
    PolygonSlow:
      type: "polygon"
      points: "[ [0.75, 0.50], [0.75, -0.50], [-0.10, -0.50], [-0.10, 0.50] ]"
      action_type: "slowdown"
      slowdown_ratio: 0.3
      enabled: True
